"""Tests for the one question the greenfield path still asks of a prompt.

This file used to test six f-string templates - a generated package, a manifest,
a `.gitignore`, a test module - and a 26-word deny list. Both are gone: #101
made the project the first *issue* of the plan, generated by the model in a
worker container, and #103 made "can this be generated" a fact about the host
rather than about the prompt's words.

Two properties survive that deletion, and they are the two this file is now
about.

**The refusal survives, and refuses earlier than it fails.** `UnsupportedStack`
is still raised, still before anything irreversible. What changed is the
predicate. A refusal that arrived after provisioning would be a repository, a
branch ruleset and a backlog somebody has to delete, which is the whole reason
#103 was last in its epic.

**Ordinary English is not a stack name**, and the stakes went *up* when the
list went away. Under the deny list a mis-resolution was a free pre-provision
error; now it is a real repository with the wrong toolchain. So that test is
kept and expanded rather than retired with the mechanism it was written for.

The per-stack verify commands moved to `bootstrap.STACK_VERIFY` and are tested
in `test_bootstrap.py`, where `test_no_stacks_gate_installs_anything` carries
forward what `test_the_verify_command_installs_nothing` used to say - the
sharpest statement of the cost tension in the old module, kept as a per-stack
rule rather than deleted with the templates.
"""

from __future__ import annotations

import pytest

from swarm.containers.manager import StackImages
from swarm.github.ledger import DEFAULT_STACK, KNOWN_STACKS
from swarm.greenfield.scaffold import (
    ScaffoldError,
    UnsupportedStack,
    choose_stack,
    main,
)

PROMPT = "a CLI that converts markdown tables to CSV"


# --------------------------------------------------------------------------
# Which stack
# --------------------------------------------------------------------------


def test_a_caller_that_resolved_no_stack_gets_the_default():
    """Not a detection result. A caller that has not resolved a stack has not
    asked a question this function can answer, and guessing from the prompt's
    words is the mechanism #103 removed."""
    assert choose_stack(PROMPT) == DEFAULT_STACK
    assert choose_stack("a React dashboard for build metrics") == DEFAULT_STACK


@pytest.mark.parametrize("stack", sorted(KNOWN_STACKS))
def test_every_stack_the_contract_allows_is_accepted(stack: str):
    """A stack a task can *declare* but the greenfield path cannot *accept* is
    a repository that provisions and then cannot be planned into."""
    assert choose_stack(PROMPT, stack=stack) == stack


def test_a_stack_is_read_case_insensitively():
    assert choose_stack(PROMPT, stack="  Node  ") == "node"


# --------------------------------------------------------------------------
# The refusal, which survived the inversion
# --------------------------------------------------------------------------


def test_the_refusal_type_survived():
    """The first criterion of #103: only the predicate changed. Every caller
    catching `UnsupportedStack` still catches it."""
    assert issubclass(UnsupportedStack, ScaffoldError)
    assert issubclass(ScaffoldError, ValueError)


def test_a_stack_with_no_image_on_this_host_is_refused_with_the_build_line():
    """The host, not the allowlist. The orchestrator can neither build nor pull
    (`BUILD=0`, `IMAGES=0`), so the remedy is a human's and the message is the
    command they run."""
    with pytest.raises(UnsupportedStack) as raised:
        choose_stack(PROMPT, stack="node", present=lambda image: False)

    assert "apiary-worker-node" in str(raised.value)
    assert "docker build -f Dockerfile.worker.node" in str(raised.value)


def test_a_stack_with_no_configured_image_says_so_differently():
    """The allowlist, not the host - fixed with an environment variable rather
    than a build. Sending an operator to the wrong one costs an hour, so the
    two messages must not be interchangeable."""
    with pytest.raises(UnsupportedStack) as raised:
        choose_stack(PROMPT, stack="python", images=StackImages(images={}))

    assert "APIARY_WORKER_IMAGES" in str(raised.value)
    assert "docker build" not in str(raised.value)


def test_a_stack_the_contract_does_not_allow_is_refused():
    with pytest.raises(UnsupportedStack) as raised:
        choose_stack(PROMPT, stack="haskell")

    assert "haskell" in str(raised.value)
    # And it names what is allowed, rather than only what is not.
    assert "python" in str(raised.value)


# --------------------------------------------------------------------------
# Ordinary English is not a stack name
# --------------------------------------------------------------------------


@pytest.mark.parametrize(
    "prompt",
    [
        "a tool to go through log files",
        "a service that lets users go back to an earlier version",
        "a c compiler explainer for beginners",
        "a rust-proofing planner for classic cars",
        "a react-ion time trainer for chemistry students",
        "a tool for node maintenance on a rail network",
        "a dashboard in TypeScript",
    ],
)
def test_ordinary_english_is_not_mistaken_for_a_stack(prompt: str):
    """Kept and expanded, and the stakes rose rather than fell.

    "go" and "c" are words before they are languages, and "rust", "react" and
    "node" all appear inside ordinary English. Under the deny list a
    mis-resolution was a free pre-provision error; now it would be a real
    repository with the wrong toolchain.

    Nothing in this module reads the prompt at all any more, which is the
    strongest possible form of this guarantee - the last row is a prompt that
    *does* name a stack, and it is still not consulted.
    """
    assert choose_stack(prompt) == DEFAULT_STACK


def test_nothing_here_reads_the_prompt():
    """The mechanism behind the test above, asserted directly: `prompt` is
    accepted for a caller's convenience and for the error messages, and is
    never a source of truth."""
    import inspect

    source = inspect.getsource(choose_stack)
    body = source.split('"""')[2]

    assert "prompt" not in body


# --------------------------------------------------------------------------
# The command
# --------------------------------------------------------------------------


def test_the_command_reports_the_stack_and_its_image(capsys):
    assert main([PROMPT, "--stack", "node"]) == 0

    out = capsys.readouterr().out
    assert "stack: node" in out
    assert "apiary-worker-node" in out


def test_the_command_writes_nothing(tmp_path, monkeypatch):
    """It used to write a project into a directory. A command that still did
    would be a second, dead generator that a contributor would reasonably read
    as the supported one."""
    monkeypatch.chdir(tmp_path)

    main([PROMPT])

    assert list(tmp_path.iterdir()) == []


def test_the_command_reports_a_refusal_instead_of_raising(capsys, monkeypatch):
    """The property this file has always protected: an operator gets a line and
    an exit code, not a traceback.

    A stack outside the contract is now rejected by argparse's `choices` before
    the function is reached, which is a better failure and not this one. So the
    refusal under test is the one argparse cannot see: a stack the contract
    allows and this host has no image configured for.
    """
    monkeypatch.setattr(
        "swarm.greenfield.scaffold.StackImages", lambda *a, **k: StackImages(images={})
    )

    assert main([PROMPT, "--stack", "node"]) == 1
    assert "APIARY_WORKER_IMAGES" in capsys.readouterr().err
