"""Which stack a greenfield repository is for, and whether this host can run it.

This module used to generate projects. It emitted six f-string templates for a
Python package - an entry point, a manifest, a test module, a `.gitignore` -
and refused any prompt naming another technology by consulting a 26-word deny
list.

**Both halves are gone, and they were removed for opposite reasons.**

The templates are gone because #101 made the project bootstrap the *first issue
of the plan*, generated by the model in a worker container with a checkout.
`Stack.build`'s `Callable[[Scaffold], dict[str, str]]` shape is simply wrong
for that: the orchestrator has no checkout and cannot get one (`EXEC=0`,
`BUILD=0`, `IMAGES=0`), so generating files there was never going to survive
contact with a second stack. `Scaffold.package` could not be generalised at all
- there is no cross-language module name - so it had to be deleted rather than
extended.

The deny list is gone because #103 inverted the question. Whether a stack can
be generated is a fact about *this machine*: #99 gives each stack a worker
image, and the answer is whether that image exists here. What survives is the
refusal itself - `UnsupportedStack`, raised before anything irreversible - and
that survival is the point. Deleting the list while the resolver still returned
Python unconditionally would have been strictly worse than keeping it: "a React
dashboard" would silently produce a Python package, after a real repository, a
branch ruleset and a backlog already existed.

What is left is one question and one refusal.

**The initial commit is deliberately almost empty.** `provision` writes a
README, a LICENSE and a workflow whose gate is `test -f README.md` - the only
command that passes on a repository with no code in it, which it has to be,
because the required status check reports on that commit before any worker
exists. The bootstrap's pull request then replaces both the files and the gate,
the latter only after #102 has watched the proposed command fail on
deliberately broken code.
"""

from __future__ import annotations

import argparse
import sys
from typing import Callable, Sequence

from ..containers.manager import ContainerError, StackImages, build_hint
from ..github.ledger import DEFAULT_STACK, KNOWN_STACKS


class ScaffoldError(ValueError):
    """A greenfield repository could not be prepared."""


class UnsupportedStack(ScaffoldError):
    """This host cannot run the stack this repository would need.

    A distinct type because the caller's response differs: it is not a bug to
    retry, it is a request to decline until somebody builds the image - and the
    message says which `docker build` line does that.

    Kept across #103's inversion on purpose. The predicate changed from "the
    prompt named a foreign technology" to "this machine has no image for it";
    the type, and every caller catching it, did not.
    """


def choose_stack(
    prompt: str,
    *,
    stack: str | None = None,
    images: StackImages | None = None,
    present: Callable[[str], bool] | None = None,
) -> str:
    """The stack id this repository is for, or `UnsupportedStack`.

    `stack` is the resolved id - `swarm run --stack`, or #101's model
    classification of the prompt. `None` means the caller has not resolved one,
    which is not a question this function can answer, so it returns the default
    rather than guessing from the prompt's words.

    Two refusals, and the message says which, because sending an operator to
    the wrong one costs an hour:

    - **no image is configured** for that stack - a fact about the allowlist,
      fixed with `APIARY_WORKER_IMAGES`;
    - **the image is configured but not built here** - a fact about the host,
      fixed with one `docker build` line, printed.

    Both are raised before anything irreversible. That ordering is the whole
    reason #103 was last in its epic: a refusal arriving after provisioning is
    a repository, a ruleset and a backlog somebody has to delete.
    """
    if stack is None:
        return DEFAULT_STACK
    chosen = stack.strip().casefold()
    if chosen not in KNOWN_STACKS:
        raise UnsupportedStack(
            f"there is no stack {chosen!r}; the contract allows "
            f"{', '.join(sorted(KNOWN_STACKS))}"
        )
    try:
        image = (images or StackImages()).for_stack(chosen)
    except ContainerError as exc:
        raise UnsupportedStack(str(exc)) from exc
    if present is not None and not present(image):
        raise UnsupportedStack(
            f"stack {chosen!r} needs image {image}, which is not on this host. "
            f"{build_hint(image)}"
        )
    return chosen


def main(argv: Sequence[str] | None = None) -> int:
    """Report which stack a repository would use, and whether this host can run it.

    All this command does now is answer the question above. It used to write a
    project into a directory; that belongs to the bootstrap issue and a worker
    container, and a command that still wrote templates would be a second, dead
    generator that a future contributor would reasonably read as the supported
    one.
    """
    parser = argparse.ArgumentParser(
        prog="swarm-scaffold",
        description="Report the stack a greenfield repository would use, and whether "
        "this host has an image for it. Writes nothing.",
    )
    parser.add_argument("prompt", help="what the project should be")
    parser.add_argument(
        "--stack",
        default=None,
        choices=sorted(KNOWN_STACKS),
        help="the stack to check (default: the contract's default)",
    )
    args = parser.parse_args(argv)

    try:
        chosen = choose_stack(args.prompt, stack=args.stack)
    except ScaffoldError as exc:
        print(f"! {exc}", file=sys.stderr)
        return 1
    print(f"stack: {chosen}")
    print(f"image: {StackImages().for_stack(chosen)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
